### ISSUE TITLE
Proposal: Switch Wording from "Deployment" to "Publish"

### ISSUE THREAD

**Issue by dlorenc** [slsa-framework/slsa#38] opened 2021-05-28 23:51 UTC
Given this is centered on artifacts, I think the term "publish" is more commonly used. In my mental model:

Deployment == fetching an artifact and running it.
Publish == building an artifact and making it available.

**Comment by MarkLodato** [comment] 2021-06-01 16:41
Dupe of #7. Let's continue the discussion there.

**Closed by MarkLodato** 2021-06-01 16:41 UTC
Labels: duplicate
