### ISSUE TITLE
Clarify the value of L1 in the source track

### ISSUE THREAD

**Issue by TomHennen** [slsa-framework/slsa#1070] opened 2024-06-17 20:04 UTC
There’ve been [outstanding questions](https://github.com/slsa-framework/slsa/pull/1037#discussion_r1569490843) on the value of L1 given that most projects already use source control.  This can definitely be clarified.

**Comment by zachariahcox** [comment] 2024-09-04 13:23
closing as a duplicate of #1112

**Closed by zachariahcox** 2024-09-04 13:23 UTC
Labels: source-track
