### ISSUE TITLE
Tracking changes

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa#167] opened 2021-09-17 13:56 UTC
Now that SLSA has its first release, we should figure out how to to communicate the differences introduced in subsequent versions. This might be as simple as a CHANGELOG which is rendered as part of slsa.dev. Or we might go more complex.

Why? Imagine someone adopts SLSA v0.1 (2021-09-16). They don't actively follow SLSA development and later come to find that SLSA 1.1 is released. How do they identify what changes they must make to be conformant with the newer SLSA version?

**Comment by joshuagl** [comment] 2022-10-03 13:35
I think we need to know how we will accomplish this prior to 1.0, even if we don't actually implement anything before 1.0 is released.

**Comment by MarkLodato** [comment] 2023-03-06 16:50
Marking as duplicate of #592.

**Closed by MarkLodato** 2023-03-06 16:50 UTC
Labels: discussion
