### ISSUE TITLE
Semantic versioning for spec

### ISSUE THREAD

**Issue by kpk47** [slsa-framework/slsa#632] opened 2023-02-22 23:21 UTC
While we don't intend to change the contents of each Build Level after releasing 1.0, we may want to have a way of signaling when such changes happen. One way to do so could be with semantic versioning (e.g. SLSA Build L3 has the same meaning for all 1.x.x releases).

**Comment by joshuagl** [comment] 2023-02-28 17:43
This seems reasonable to me. I think many assume semantic versioning, even if it's not intended, so being explicit here will help us and any readers.

**Comment by arewm** [comment] 2023-03-02 16:30
It is important to not only have explicit semantic versioning for the overall SLSA specification but also enabling an accurate semantic versioning standard for each of the tracks. I assume that no changes to individual tracks will be changed without also changing the overall version. Is there a way that we can infer what might have changed in any of the tracks when seeing only the version change in the overall specification?

**Comment by MarkLodato** [comment] 2023-03-06 16:52
Marking as a duplicate of #570.

**Closed by MarkLodato** 2023-03-06 16:52 UTC
