### ISSUE TITLE
postpone Non-falsifiable provenance requirement for after 1.0

### ISSUE THREAD

**Issue by JanZerebecki** [slsa-framework/slsa#467] opened 2022-08-15 14:37 UTC
This is in the context of the plan that anything level 4 and all source requirements will not be included in 1.0.

(The following was moved to an issue from https://github.com/slsa-framework/slsa-proposals/pull/5#issuecomment-1212157441 .)

In level 1-3 of the requirements the Non-falsifiable provenance requirement is as written too early in the levels compared to how 1.0 will look now. And the technical requirements are not properly explained or not detailed enough or misleading. Can we also remove that for 1.0 and work on it afterwards?

Details for why Non-falsifiable needs to be fixed:
Rerunning the providence generator is easier than the build itself. It should be possible to generate providence in a reproducible way. Both economically and security wise it doesn't make sense to sign anything for security purposes before you have put work into verifiable reproducible builds. If you don't have evidence for a good build and just sign something, one might think: oh there is a signature, must be secure. Even when you have reproducible builds, so that you have some falsifiable evidence for non-compromised builds, then: Signing keys in a "secure management system appropriate for such material" is under specified. Most of the software to sign stuff is architecturally less secure than GPG and TUF, so if we go by the average understanding, that will lead people to put work in adopting worse. Even TUF can be used, with some effort, in a way, that is not a good idea, so we need to say what we mean. Etc.

**Comment by MarkLodato** [comment] 2022-08-15 14:45
Sorry, I don't understand this suggestion. On its face, I don't agree with removing this requirement from SLSA 3. I've not heard anyone else suggesting this idea. The "non-falsifiable" requirement is the main difference between SLSA 2 and SLSA 3; Isolated and Ephemeral Environment are really just necessary items to get the "non-falsifiable" property.

**Comment by JanZerebecki** [comment] 2022-08-15 16:38
A slightly different wording of what I'm asking for: The Non-falsifiable requirement (which is mostly about signing) should depend on verified reproducible builds.

Ironically I'm asking for it to be falsifiable in the scientific sense, as in a testable assertion. So non-counterfeit-able would be a less confusing wording for the requirement.

> The "non-falsifiable" requirement is the main difference between SLSA 2 and SLSA 3;

That is only true of the provenance requirements, not the build requirements. The level 3 build requirements and the level 2 provenance requirements are worth it on its own and together, without a signature.

> Isolated and Ephemeral Environment are really just necessary items to get the "non-falsifiable" property.

They are not "just necessary" (as in "only necessary"), they are useful on their own. The additional issue is that there is a step missing, that only comes in later levels. Verified reproducible builds make it possible to have evidence for showing Isolated and Ephemeral Environment were correctly done. Signing that evidence is useful.

> I've not heard anyone else suggesting this idea.

This is implicit in what people do at reproducible-builds.org , so it is in a sense implicit in https://github.com/slsa-framework/slsa/issues/5 , except that this is the logical continuation of postponing it and level 4.

### Examples:

By now Debian requires binary reproducible builds. Before this, binaries were signed without provenance. To show provenance you need a way to show that the chain of evidence is not compromised (instead of merely not knowing of any compromise). To sign a statement about provenance without being able to show provenance might be tempting, but it does not match real world causality.

Even if one found at some point evidence that a binary was compromised, the signed provenance as of SLSA 0.1 doesn't allow anyone to tell what exactly is compromised. A  way to show what else is compromised is thus lacking, so one also doesn't have a way to get to an non-compromised state.

One could spend a lot of effort on signing the statement "Uri Geller can bend spoons with his mind.". Instead one should first spend effort in how to collect evidence, how to devise a scientific test that will tell us what happened.

Otherwise it would be like thinking about a costly lock (signing) without checking if the door is sturdy.

One can always rebuild and thus skip checking any signature of the binary or its provenance. But reproducible builds provide more security in either way, so they are always worth more than a signature by itself.

**Comment by JanZerebecki** [comment] 2022-08-15 16:40
Is it now understandable for you?

**Comment by dlorenc** [comment] 2022-08-15 17:21
> Both economically and security wise it doesn't make sense to sign anything for security purposes before you have put work into verifiable reproducible builds.

I disagree with that premise here. Verified reproducible builds are a good thing, but I disagree they're the only way to obtain the properties sought after by SLSA. Which approach makes the most sense economically is subjective, and different approaches make sense in different places.

**Comment by JanZerebecki** [comment] 2022-08-15 19:19
My argument was that the proposed version of SLSA under discussion here doesn't provide the properties.

I can think of a situation in which the current proposal would still make sense for some people. Many things are non-objective, but still scientific, so SLSA should explain the situation in which they make sense. If it is as intended, then I don't think the proposed version does explain it clearly enough.

Maybe we disagree about which properties SLSA should seek. Which are you thinking of?

Can you give an example of another way to bring a scientific argument for reliably detecting if a binary is compromised (threat D of SLSA 0.1)?

**Comment by shaunmlowry** [comment] 2022-09-26 15:56
I still think there's value in non-falsifiability of claims here, and I think the statement that there's no point in signing provenance until you've reached SLSA 4 including the optional requirements.  If nothing else, you can prove that the subject artifact has not changed since the attestation was made if the attestation has a signature as it acts as a proxy signature for the artifact in this case.

Would be happy to defer this until there's a clear demonstration that signatures serve no purpose without an ideal build and source chain

**Comment by MarkLodato** [comment] 2022-10-17 20:41
The main point of this issue, as I understand it, is to either add a requirement around verified reproducible builds at Build L3 or remove the wording around "non-falsifiable" because the claim is too strong. There have been no comments in favor but several against, so I am going to say that the consensus is not to do this and close this issue.

It sounds like the last comment also touches on the [evidence of build security claims](https://github.com/slsa-framework/slsa-proposals/blob/main/0003/README.md#evidence-of-build-service-security-claims), which is indeed planned for v1.0.

**Closed by MarkLodato** 2022-10-17 20:41 UTC
Labels: spec-change, slsa 3, maybe-1.0
